# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.photo_btn = QtWidgets.QPushButton(self.centralwidget)
        self.photo_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_btn.sizePolicy().hasHeightForWidth())
        self.photo_btn.setSizePolicy(sizePolicy)
        self.photo_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.photo_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.photo_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.photo_btn.setObjectName("photo_btn")
        self.verticalLayout.addWidget(self.photo_btn, 0, QtCore.Qt.AlignHCenter)
        self.test_btn = QtWidgets.QPushButton(self.centralwidget)
        self.test_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.test_btn.setObjectName("test_btn")
        self.verticalLayout.addWidget(self.test_btn, 0, QtCore.Qt.AlignHCenter)
        self.off_btn = QtWidgets.QPushButton(self.centralwidget)
        self.off_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.off_btn.setObjectName("off_btn")
        self.verticalLayout.addWidget(self.off_btn, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.photo_btn.setText(_translate("MainWindow", "Photo"))
        self.test_btn.setText(_translate("MainWindow", "Test"))
        self.off_btn.setText(_translate("MainWindow", "Off"))
