# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, 10, 20, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.get_score_btn = QtWidgets.QPushButton(self.centralwidget)
        self.get_score_btn.setEnabled(False)
        self.get_score_btn.setObjectName("get_score_btn")
        self.verticalLayout_2.addWidget(self.get_score_btn)
        self.score_line = QtWidgets.QLineEdit(self.centralwidget)
        self.score_line.setEnabled(True)
        self.score_line.setReadOnly(True)
        self.score_line.setObjectName("score_line")
        self.verticalLayout_2.addWidget(self.score_line)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.retry_btn = QtWidgets.QPushButton(self.centralwidget)
        self.retry_btn.setEnabled(False)
        self.retry_btn.setObjectName("retry_btn")
        self.verticalLayout_3.addWidget(self.retry_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setEnabled(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.verticalLayout_3.addWidget(self.cancel_btn)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_btn = QtWidgets.QPushButton(self.centralwidget)
        self.image_btn.setEnabled(True)
        self.image_btn.setObjectName("image_btn")
        self.verticalLayout.addWidget(self.image_btn)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(256, 256))
        self.label.setMaximumSize(QtCore.QSize(256, 256))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_score_btn.setText(_translate("MainWindow", "Get score"))
        self.retry_btn.setText(_translate("MainWindow", "Retry"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.image_btn.setText(_translate("MainWindow", "photo"))
